# =================================
# = Spring
# =================================

spring:
  datasource:
    url: jdbc:mysql://realmeet-db.ctutyr5cop4a.sa-east-1.rds.amazonaws.com:3306/gooffice?&serverTimezone=UTC&useSSL=false
    username: admin
